Delete README.md
Recently I installed mraa library in Edison kit for arduino.Then I try to identify version of this. But mraa doesn't work properly.Node.js I updated v0.10.38 to v4.4.3 doesn't show version of mraa .Following is output.

var m =require('mraa');
Error: Cannot find module 'mraa'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at repl:1:8
at REPLServer.defaultEval (repl.js:262:27)
at bound (domain.js:287:14)
at REPLServer.runBound [as eval] (domain.js:300:12)
at REPLServer. (repl.js:431:12)
at emit0ne (events.js:82:20)

Does anyone help me?